<?php

namespace MBH\SitederencontreBundle\Repository;

/**
 * MembersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembersRepository extends \Doctrine\ORM\EntityRepository
{
}
